PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE student(
username varchar(30),
register_no varchar(20) PRIMARY KEY,
department varchar(20) NOT NULL,
date_of_birth varchar(20) NOT NULL,
email varchar(200) NOT NULL
);
INSERT INTO student VALUES('Kannadhasan S','510422104050','CSE','25-06-2005','kannadhasansivakumar2005@gmail.com');
INSERT INTO student VALUES('Mohan S','510421104060','CSE','09-03-2001','mohansri177@gmail.com');
INSERT INTO student VALUES('Kathiravan T','510422104053','CSE','25-06-2005','kannadhasansivakumar2005@gmail.com');
INSERT INTO student VALUES('shyam','510422104099','cse','10-11-2004','6369533122shyam@gmail.com');
INSERT INTO student VALUES('Balaganeshan','510422104019','CSE','22-11-2005','balaganeshan196@gmail.com');
CREATE TABLE books(
book_id varchar(200),
book_name varchar(200),
author varchar(200),
number_of_pages int,
published_year int,
publisher varchar(200),
description text,
book_count int,
image_url varchar(200),
chapters text);
INSERT INTO books VALUES('1233jjfjn3322','Discrete Event System Simulation','Jerry Banks, John Carson, Barry Nelson, David Nicol',530,2009,'Prentice Hall of India',replace('This book provides a comprehensive look at discrete-event simulation, emphasizing principles that can\nbe applied universally to simulation software. It covers fundamental aspects such as statistical models, data analysis, and validation techniques, with real-world applications in manufacturing, computer systems, and networks. It includes practical exampl\nes, figures, and exercises to enhance understanding of these concepts. It’s particularly useful for engineering, computer science, and operations research fields.','\n',char(10)),5,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729052225/Discrete_event_system_simulation_oiqzku.webp',replace(' Introduction to Simulation # Simulation Examples #General Principles # Simulation Software # Statistical Models in Simulation # Queueing Models\n# Random-Number Generation # Random-Variate Generation # Input Modeling # Verification and Validation of Simulation Models # Output Analysis for a Single Model\n# Comparison and Evaluation of Alternative System Designs # Simulation of Manufacturing and Material-Handling Systems # Simulation of Computer Systems # Simulation of Computer Networks','\n',char(10)));
INSERT INTO books VALUES('9eb6c195-cef7-46bf-abb2-c5930bb5b730','Computer Architecture and  Organization','John Hayes',604,1998,'Tata Mc Graw Hill',replace('Computer Architecture and Organization" by John P. Hayes is a fundamental textbook designed to introduce readers to the internal workings of computers. It delves into both the structural aspects of computer systems (architecture) and the operational aspects (organization), providing a holistic view of how computers process data, execute instructions, and manage hardware resources.\n\nThe book begins with an introduction to basic computer concepts, laying the groundwork for topics like digital logic circuits, processor design, memory hierarchy, input/output mechanisms, and the overall control of systems. Hayes meticulously explains the architecture of modern computers, covering essential components such as the central processing unit (CPU), memory, and buses, while focusing on performance optimization through techniques like pipelining and parallelism. In addition to explaining hardware mechanisms, it offers detailed discussions on computer arithmetic, instruction sets, and the role of microprogramming in controlling the CPU.','\n',char(10)),2,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729059596/718Rdq_LT2L._SY466__yjugo5.jpg','Introduction to Computing and Computer Systems#Design Methodology#Processor Basics#Datapath Design#Control Design#Memory Organization#System Organization');
INSERT INTO books VALUES('5a8f8e5d-4a83-4c3e-babc-8cb67eb62dbc','Object Oriented Analysis and Design','MikeDocherty',574,2002,' Pearson Education  Asia','The book Object-Oriented Analysis and Design: Understanding System Development with UML 2.0 by Mike ODocherty provides a comprehensive introduction to object-oriented concepts, focusing on the entire software development process. It is structured to follow the key steps of a typical development project, from requirements capture through design, specification, and testing, using UML 2.0 to model and document the system. The book emphasizes a practical approach, incorporating a single case study throughout to guide readers from an abstract problem to a detailed solution.',2,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729082434/1_exgpdl.jpg','Introduction to Object-Oriented Systems # Understanding Object-Oriented Concepts # Software Development Processes # Using UML for Modeling # Requirements Capture # Design Specification # Testing Object-Oriented Systems # Case Study: A Step-by-Step Development');
INSERT INTO books VALUES('a4847f08-5c0e-43ee-93ca-dfeb104cd775','Analysis and Design of information  system','James Senn',534,1986,'Tata Mc Graw Hill','The book "Analysis and Design of Information Systems" by James A. Senn, published by Tata McGraw-Hill in 1989, is a key resource for understanding the methodologies and practices in information systems design. It provides comprehensive coverage of structured systems analysis, design techniques, and project management approaches in IT.',2,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729084107/9780071006064-us_scyyhl.jpg','Introduction to Information Systems # Systems Development Life Cycle (SDLC) # Data Flow Diagrams (DFD) # Database Design and Management # Structured Analysis and Design Techniques # Project Management in Information Systems # System Implementation and Testing # Case Studies in Systems Design');
INSERT INTO books VALUES('1a3006a9-5622-4e27-b646-58e3fcaf3f81','Turbo C++','Robert Lafore',776,2002,'Galgotia Publication',replace('Turbo C++ by Robert Lafore is a comprehensive guide designed to teach the principles of object-oriented programming (OOP) using the Turbo C++ environment. The book begins with an introduction to C++ syntax and gradually transitions into more complex concepts, making it suitable for both beginners and intermediate programmers.\n\nLafore emphasizes foundational OOP concepts such as classes, objects, inheritance, polymorphism, and encapsulation. Each chapter includes clear explanations, practical examples, and exercises that encourage hands-on learning. The book also addresses advanced topics like templates, exception handling, and file manipulation, providing readers with a robust understanding of programming in C++.','\n',char(10)),3,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729084505/9788185623221.OL.0.m_xawlum.jpg','Introduction to C++ and Turbo C++ # Fundamentals of Object-Oriented Programming # Classes and Objects # Constructors and Destructors # Operator Overloading # Inheritance # Polymorphism and Virtual Functions # Templates and Exception Handling # Streams and File Handling in C++ # Advanced OOP Concepts');
INSERT INTO books VALUES('ea1fbe7a-85ba-41f0-9bfe-1954ce1d6060','Perl 5 How-To','Mc Millan',401,1998,'Techmedia  Publication','Perl 5 How-To is a practical guide offering more than 200 Perl programming solutions. It covers common problems, provides detailed explanations, and presents step-by-step solutions, making it an invaluable resource for Perl users.',2,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729085173/744EA3482DAB08474095B7999739EA95E426A5CB_fwu9ad.jpg','Getting Started#Scalar Variables#Arrays#Hashes#Subroutines#Control Structures#File Handling#Regular Expressions#Error Handling#Object-Oriented Perl.');
INSERT INTO books VALUES('27111c54-8acd-44eb-8cd6-83c0a3744f9c','Operating System','William Stallings',864,2012,'Prentice Hall of  India','The book "Operating System" by William Stallings, published by Prentice Hall of India in 2012, provides a comprehensive overview of operating system concepts, design, and implementation. It covers various topics such as process management, memory management, file systems, and security.',2,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729086499/size-W370-A1030-00-26-03-A103000260387-A103000260387-Lrg_xdffzx.avif','Introduction to Operating Systems#Process Management#Threads#CPU Scheduling#Process Synchronization#Deadlocks#Memory Management#Virtual Memory#File Systems#I/O Systems#Security and Protection#Case Studies');
INSERT INTO books VALUES('0e277dca-307e-4a7e-ae1c-3e56b4ea4108','Foundation Of Data Science','I.A.Dhotre',191,2022,'Technical Publication','The book "Fundamentals of Data Science and Analytics for BE Anna University R21CBCS (III- CS & BS & Semester - IV AI&DS- AD3491)" is a comprehensive guide that introduces key concepts and techniques in data science and analytics.',1,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729087392/11_fuqccs.webp',' Introduction to Data Science#Descriptive Analytics#Inferential Statistics#Analysis of Variance (ANOVA)#Predictive Analytics');
INSERT INTO books VALUES('a77645e6-154e-4bbb-ae27-d7ed1ddd5d3e','Algorithms','A.A.Puntambeka',532,2023,'Technical Publication','Algorithm analysis : Time and space complexity - Asymptotic Notations and its properties Best case, Worst case and average case analysis - Recurrence relation : substitution method - Lower bounds - searching : linear search, binary search and Interpolation Search, Pattern search : The naïve string - matching algorithm - Rabin-Karp algorithm - Knuth-Morris-Pratt algorithm. Sorting : Insertion sort - heap sort. (Chapter - 1) UNIT II GRAPH ALGORITHMS Graph algorithms : Representations of graphs - Graph traversal : DFS - BFS - applications - Connectivity, strong connectivity, bi-connectivity - Minimum spanning tree: Kruskal’s and Prim’s algorithm - Shortest path : Bellman - Ford algorithm - Dijkstra’s algorithm - Floyd-Warshall algorithm Network flow : Flow networks - Ford-Fulkerson method - Matching : Maximum bipartite matching. (Chapter - 2) UNIT III ALGORITHM DESIGN TECHNIQUES Divide and Conquer methodology : Finding maximum and minimum - Merge sort - Quick sort Dynamic programming : Elements of dynamic programming - Matrix-chain multiplication - Multi stage graph - Optimal Binary Search Trees. Greedy Technique : Elements of the greedy strategy - Activity-selection problem - Optimal Merge pattern - Huffman Trees. (Chapters - 3, 4, 5) UNIT IV STATE SPACE SEARCH ALGORITHMS Backtracking : n-Queens problem - Hamiltonian Circuit Problem - Subset Sum Problem - Graph colouring problem Branch and Bound : Solving 15-Puzzle problem - Assignment problem - Knapsack Problem - Travelling Salesman Problem. (Chapter - 6) UNIT V NP-COMPLETE AND APPROXIMATION ALGORITHM Tractable and intractable problems : Polynomial time algorithms - Venn diagram representation - Np - algorithms - NP-hardness and NP-completeness - Bin Packing problem - Problem reduction : TSP - 3 - CNF problem. Approximation Algorithms : TSP - Randomized Algorithms : concept and application - primality testing - randomized quick sort - Finding kth smallest number',1,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729087700/9789_x8j28q.webp','Introduction to Algorithms#Mathematical Foundations#Analysis of Algorithms#Divide and Conquer#Greedy Algorithms#Dynamic Programming#Graph Algorithms#NP-Completeness#Approximation Algorithms#Randomized Algorithms#Algorithm Design Techniques#Sorting and Searching Algorithms#Complexity Theory#Algorithm Applications#Advanced Data Structures');
INSERT INTO books VALUES('e445fef5-73a6-4e1b-ae4d-33d41c22a75d','Artificial Intelligence and Meachine Learning','I.A.Dhotre & Anamithra  Deshmukh Nimbalkar',202,2023,'Technical Publication','This book covers a wide range of topics including problem-solving agents, search algorithms, probabilistic reasoning, supervised and unsupervised learning, and neural networks, providing a robust framework for understanding AI and machine learning concepts.',1,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729087996/9789390770229_3_52eeb9fc-380e-439e-a688-a4d14964524c_640x_crop_center_bc8oif.webp','Problem Solving # Search Algorithms # Informed Search Strategies # Heuristic Search Strategies # Adversarial Search # Constraint Satisfaction Problems (CSP) # Probabilistic Reasoning # Supervised Learning # Ensemble Techniques and Unsupervised Learning # Neural Networks');
INSERT INTO books VALUES('941282a8-7495-4852-b09d-c0186feab44d','Problem Solving and Python Programming',' Dr. V. Ramesh Babu, M. Munirathnam',248,2,'VRB Publishers','"Problem and Python Programming" by Dr. V. Ramesh Babu and M. Munirathnam provides a comprehensive introduction to problem-solving techniques using Python. It covers fundamental programming concepts and practical applications, enabling readers to develop robust programming skills.',2,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729088415/PSP-475x475_fsvpcu.jpg','Introduction to Problem Solving # Introduction to Python # Data Types and Operators # Control Statements # Functions and Modules # Strings and Lists # Dictionaries and Tuples # File Handling # Object-Oriented Programming # Data Structures and Algorithms');
INSERT INTO books VALUES('322a9c77-91d1-4bde-a91d-fa478d448aa3','Data Warehousing and Data Mining',' R. Ruhin Kouser, V. Gunasundhari, Lakshmi',450,2015,'Lakshmi Publications','The book Data Warehousing and Data Mining by R. Ruhin Kouser, V. Gunasundhari, and Lakshmi, published in 2015 by Lakshmi Publications, contains a comprehensive exploration of the concepts and techniques in data warehousing and data mining.',3,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729088817/61BJg5Bi-YL._AC_UY327_FMwebp_QL65__mta2oi.webp','Introduction to Data Warehousing # Data Warehouse Architecture # Data Mining Techniques # ETL Processes (Extract, Transform, Load) # Data Analysis and Visualization # Case Studies in Data Warehousing # Future Trends in Data Warehousing and Mining');
INSERT INTO books VALUES('057d2f50-a140-45af-bc6a-3d79e50ff847','Design and Analysis of Algorithms','S. Kavitha and V. Balasubramanian',424,2017,'Magnus Publication','Design and Analysis of Algorithms by S. Kavitha and V. Balasubramanian is a comprehensive resource focused on fundamental concepts in algorithms. This book covers essential techniques and theories needed to design efficient algorithms, alongside practical examples and problem-solving strategies relevant to various domains in engineering and technology.',4,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729089043/8_l1lnc6.png','Basics of Algorithm Writing, Iterative and Recursive Algorithms # Analysis of Iterative Algorithms # Exhaustive Searching and Combinatorial Optimization Problems # Divide and Conquer Technique # More Decrease and Conquer Algorithms # More Applications of Divide and Conquer # Transform and Conquer Design Paradigm');
INSERT INTO books VALUES('7eec40cd-9d48-4c56-8965-916a91b58a36','Digital Principles and System Design','A.P. Godse and D.A. Godse',424,2017,'Technical  Publication','Digital Principles and System Design by A.P. Godse and D.A. Godse is a comprehensive textbook that covers the essential concepts and applications of digital principles and system design. It is designed as per the Common Syllabus for Anna University, making it suitable for undergraduate students in Computer Science and IT. The book includes chapter-wise solved questions from previous exams, enhancing the learning experience and helping students prepare effectively.',4,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729089361/9789333219143_5_640x_crop_center_xkvzey.webp','Digital Systems # Number Systems # Logic Gates # Boolean Algebra # Combinational Circuits # Sequential Circuits # Register Transfer Language # Memory and Storage # Digital Integrated Circuits # Programmable Logic Devices # Design of Sequential Circuits # Testing of Digital Circuits');
INSERT INTO books VALUES('1adb63ec-a258-4ff2-976c-cf7c7cb727fe','Distributed Computing','DR. S. Padmapriya',390,2016,'Sruthi Publishers','Distributed Systems by Padmapriya offers a comprehensive overview of the principles and concepts underlying distributed computing. It explores the design, implementation, and management of distributed systems, emphasizing real-world applications and challenges. The text covers key topics such as architectural models, communication protocols, synchronization methods, fault tolerance, and security measures. Additionally, it addresses emerging trends in technology that impact distributed systems, providing insights into both theoretical foundations and practical applications.',3,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729089800/magnus-distributed-computing-550x550h_ql7su1.jpg','Introduction to Distributed Systems#Architectural Models#Communication in Distributed Systems#Synchronization#Consistency and Replication#Fault Tolerance#Security in Distributed Systems#Quality of Service (QoS)#Middleware for Distributed Systems#Challenges in Distributed Systems#Emerging Trends in Distributed Systems#Case Studies');
INSERT INTO books VALUES('5b24d722-d240-4dd4-a9d6-00efd8c246d9','Principles of Management ','Dr. G.K. Vijayaraghavan, Dr. M. Sivakumar',715,2015,'Lakshmi  Publications','The book Principles of Management by Dr. G.K. Vijayaraghavan and Dr. M. Sivakumar is designed for students of engineering, particularly for those in their 6th, 7th, and 8th semesters across disciplines such as Mechanical, Mechatronics, Aeronautical, and Electrical Engineering. It follows the syllabus of Anna University.',2,'https://res.cloudinary.com/dn6izpj6p/image/upload/v1729154786/principles-of-management-78579_tyfunc.jpg','Management Fundamentals # Planning # Organizing # Directing # Controlling');
COMMIT;
